### ISSUE TITLE
Master branch fails with the same errors

### ISSUE THREAD

**Issue by tiberiuichim** [collective/awesome-volto#14]
Looks like also master branch fails with the same errors:
```
Dupes 
  1. [L047] https://github.com/collective/volto-authomatic
  2. [L131] https://github.com/collective/volto-vocabulary-icons-widget
  3. [L142] https://github.com/collective/volto-data-grid-widget
```

Can you or someone else take a look and remove the duplicate entries, please?

_Originally posted by @avoinea in https://github.com/collective/awesome-volto/issues/13#issuecomment-1282667777_

**Comment by instification** [comment]
Looks like the dupes were fixed by @tiberiuichim in master.

The failing tests are now all either 429 errors from github, a 503 on the simples consortia website and a redirect for pretagov which is resolved by #13
